apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lkcin5xpd-go
  janus-idp.io/tekton: lkcin5xpd-go
  backstage.io/kubernetes-id: lkcin5xpd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lkcin5xpd-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
