apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lkcin5xpd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lkcin5xpd-go 
  name: lkcin5xpd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lkcin5xpd-go 
